### PR TITLE
fixed path matching with dashed parameters

### PR DESCRIPTION
**Pull request by buldezir**

### CODE REVIEW

**Comment by lukashin** [comment]
Please add test

**Comment by Dropaq** [comment]
This naming convention for placeholders was never supported.

 implementation in this PR is too narrow in scope and should at least consider underscores then. Having only dash supported is rather confusing

**Comment by buldezir** [comment]
> This naming convention for placeholders was never supported.
> 
> implementation in this PR is too narrow in scope and should at least consider underscores then. Having only dash supported is rather confusing

https://www.php.net/manual/en/regexp.reference.escape.php
> A "word" character is any letter or digit or the underscore character....

**Comment by lukashin** [comment]
@Dropaq what are you doing here exactly? :trollface:

**Review by lukashin — APPROVED** [review]

**Pull request merged**
