### PR TITLE
Updated version constraints for psr/http-message

### PR DESCRIPTION
**Pull request by akryvushenko**
relates to #34

### CODE REVIEW

**Review by a1ryabykina — APPROVED** [review]

**Comment by aivus** [comment]
@akryvushenko https://github.com/auto1-oss/service-api-client-bundle/pull/34 is already merged, do we need to update `psr/http-message`?

**Comment by akryvushenko** [comment]
> @akryvushenko #34 is already merged, do we need to update `psr/http-message`?

I will check merged version and come back with info

**Comment by akryvushenko** [comment]
> @akryvushenko #34 is already merged, do we need to update `psr/http-message`?

We don't need this update. I'll close pr

**Comment by akryvushenko** [comment]
> @akryvushenko #34 is already merged, do we need to update `psr/http-message`?

We don't need this update. I'll close pr

**Pull request closed without merging**
